version: '3.8'

services:
  sig-provider_l1:
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'sig-provider_l1'
    ports:
      - 8151:8050
